<?xml version="1.0"?>
<!DOCTYPE Report [
	<!ELEMENT Report (General ,(Doc|BPT))>
	<!ATTLIST Report
		ver CDATA #REQUIRED
		tmZone CDATA #REQUIRED
	>
	<!ELEMENT General ( DocLocation )>
	<!ATTLIST General
		productName CDATA #REQUIRED
		productVer CDATA #REQUIRED
		os CDATA #REQUIRED
		host CDATA #REQUIRED
		qcserver CDATA #IMPLIED
		qcproject CDATA #IMPLIED
		SolManSolutionId CDATA #IMPLIED
		SolManProjectId CDATA #IMPLIED
		SolManTestPlanId CDATA #IMPLIED
		SolManTestPackageId CDATA #IMPLIED
		SolManUserInfoData CDATA #IMPLIED
	>
	<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*)>
	<!ATTLIST BPT rID ID #REQUIRED>
	<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?)>
	<!ATTLIST Doc
		rID ID #REQUIRED
		type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test"
		productName CDATA #REQUIRED
		BCIter CDATA #IMPLIED
	>
	<!ELEMENT RunType ( #PCDATA )>
	<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">
	<!ELEMENT DName ( #PCDATA )>
	<!ELEMENT ConfName ( #PCDATA )>
	<!ELEMENT Res ( #PCDATA )>
	<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue )>
	<!ELEMENT AdditionalDataName ( #PCDATA )>
	<!ELEMENT AdditionalDataValue ( #PCDATA )>
	<!ELEMENT DVer ( #PCDATA )>
	<!ELEMENT TSet ( #PCDATA )>
	<!ELEMENT TInst ( #PCDATA )>
	<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
	<!ATTLIST DIter
		rID ID #REQUIRED
		iterID CDATA #REQUIRED
	>
	<!ELEMENT DocLocation ( #PCDATA )>
	<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs )>
	<!ATTLIST Action rID ID #REQUIRED>
	<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs)>
	<!ATTLIST AIter
		rID ID #REQUIRED
		iterID CDATA #REQUIRED
		isCountable (False|True) "False"
	>
	<!ELEMENT AName ( #PCDATA )>
	<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*)>
	<!ATTLIST TestMaintenanceSummary
		ObjectsAdded CDATA #REQUIRED
		ObjectsUpdated CDATA #REQUIRED
		StepsUpdated CDATA #REQUIRED
		StepsComments CDATA #REQUIRED
	>
	<!ELEMENT ActionMaintenanceSummary (ObjectChange* )>
	<!ATTLIST ActionMaintenanceSummary
		Action CDATA #REQUIRED
		Objects CDATA #REQUIRED
		Updated CDATA #REQUIRED
		LinesTotal CDATA #REQUIRED
		Added CDATA #REQUIRED
		LinesUpdated CDATA #REQUIRED
	>
	<!ELEMENT ObjectChange (Hierarchy, PropertyChangeList* )>
	<!ATTLIST ObjectChange
		Operation CDATA #IMPLIED
		OriginalRepository CDATA #IMPLIED
	>
	<!ELEMENT PropertyChangeList (PropertyDef*)>
	<!ELEMENT PropertyDef (OriginalValue, NewValue)>
	<!ATTLIST PropertyDef
		PropName CDATA #REQUIRED
		OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False"
	>
	<!ELEMENT OriginalValue ( #PCDATA )>
	<!ELEMENT NewValue ( #PCDATA )>
	<!ELEMENT Hierarchy (ObjectName, Hierarchy*)>
	<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>
	<!ELEMENT ObjectName ( #PCDATA )>
	<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs)>
	<!ATTLIST Step
		rID ID #REQUIRED
		retval CDATA #IMPLIED
	>
	<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs)>
	<!ATTLIST HtmlStep rID ID #REQUIRED>
	<!ELEMENT Obj ( #PCDATA )>
	<!ATTLIST Obj plainTxt (False|True) "True">
	<!ELEMENT Details ( #PCDATA )>
	<!ATTLIST Details plainTxt (False|True) "True">
	<!ELEMENT Time ( #PCDATA )>
	<!ELEMENT HTML ( #PCDATA )>
	<!ELEMENT Disp ( #PCDATA )>
	<!ELEMENT TimeTick ( #PCDATA )>
	<!ELEMENT DataMapping ( DataMappedItem* )>
	<!ELEMENT DataMappedItem EMPTY>
	<!ATTLIST DataMappedItem dsName CDATA #REQUIRED>
	<!ATTLIST DataMappedItem rowId CDATA #REQUIRED>
	<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
	<!ATTLIST NodeArgs
		eType CDATA #REQUIRED
		icon CDATA #REQUIRED
		nRep CDATA #REQUIRED
		UserNote CDATA #IMPLIED
		filter (False|True) "True"
	>
	<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
	<!ATTLIST NodeArgs
		iconSel CDATA #IMPLIED
		nType CDATA #IMPLIED
		MovieMarker CDATA ""
	>
	<!ATTLIST NodeArgs
		Source CDATA #IMPLIED
		SourceLine CDATA #IMPLIED
		StepFlowItemKey CDATA #IMPLIED
	>
	<!ELEMENT TopPane (Path)>
	<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
	<!ATTLIST BtmPane vType CDATA "HTML">
	<!ELEMENT Path ( #PCDATA )>
	<!ELEMENT ASHilite ( #PCDATA )>
	<!ELEMENT WR ( #PCDATA )>
	<!ELEMENT ExtendedInfo ( StepData )>
	<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
	<!ELEMENT DT (NodeArgs)>
	<!ATTLIST DT rID ID #REQUIRED>
	<!ELEMENT Summary (Param*)>
	<!ATTLIST Summary
		sTime CDATA #IMPLIED
		eTime CDATA #IMPLIED
		passed CDATA #IMPLIED
		failed CDATA #IMPLIED
		warnings CDATA #IMPLIED
		retval CDATA #IMPLIED
		stopped (False|True) "False"
	>
	<!ELEMENT Param (ParamName,ParamVal)+>
	<!ATTLIST Param paramInOut (In|Out) "In">
	<!ELEMENT ParamName ( #PCDATA )>
	<!ELEMENT ParamVal ( #PCDATA )>
]>
<Report ver="2.0" tmZone="Paris, Madrid">
	<General productName="Micro Focus Unified Functional Testing" productVer="15.0.1" os="" host="SFVIA018" qcserver="http://z6i7222v.itsoc.itmma.fr:8080/qcbin" qcproject="VNR.VALIDATION_2012">
		<DocLocation>
			<![CDATA[[ALM] Subject\QTP Tests\P9\MRH_2018\SCENARIO_01\MRH_M_SC01_CAS01_AN]]>
		</DocLocation>
	</General>
	<Doc rID="T1" productName="Micro Focus Unified Functional Testing">
		<DName>
			<![CDATA[MRH_M_SC01_CAS01_AN]]>
		</DName>
		<Res>
			<![CDATA[TempResults]]>
		</Res>
		<DT rID="T2">
			<NodeArgs eType="Table" icon="2" nRep="5" filter="False">
				<Disp>
					<![CDATA[Run-Time Data Table]]>
				</Disp>
				<BtmPane vType="Table">
					<Path>
						<![CDATA[Default.xlsx]]>
					</Path>
				</BtmPane>
			</NodeArgs>
		</DT>
		<DIter rID="T3" iterID="1">
			<Action rID="T4">
				<AName>
					<![CDATA[MRH_M_SC01_CAS01_AN]]>
				</AName>
				<Action rID="T5">
					<AName>
						<![CDATA[DebutTest [DebutTest]]]>
					</AName>
					<Action rID="T6">
						<AName>
							<![CDATA[Initialisations [Initialisations] [2]]]>
						</AName>
						<Step rID="T7">
							<Obj>
								<![CDATA[Début de test]]>
							</Obj>
							<Details>
								<![CDATA[Effectue les opérations communes en début de test]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:11]]>
							</Time>
							<TimeTick>1648626011</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="11" status="Passed" Source="Initialisations [Initialisations] [2]" SourceLine="5">
								<Disp>
									<![CDATA[Début de test]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T8">
							<Obj>
								<![CDATA[Le Poste de Travail utilisé est : SFVIA018]]>
							</Obj>
							<Details>
								<![CDATA[]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:11]]>
							</Time>
							<TimeTick>1648626011</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="12" Source="Initialisations [Initialisations] [2]" SourceLine="6">
								<Disp>
									<![CDATA[Le Poste de Travail utilisé est : SFVIA018]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T9">
							<Obj>
								<![CDATA[L'environnement Windows est : Windows 10 Enterprise]]>
							</Obj>
							<Details>
								<![CDATA[]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:11]]>
							</Time>
							<TimeTick>1648626011</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="13" Source="Initialisations [Initialisations] [2]" SourceLine="7">
								<Disp>
									<![CDATA[L'environnement Windows est : Windows 10 Enterprise]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T10">
							<Obj plainTxt="False">
								<![CDATA[SystemUtil]]>
							</Obj>
							<Details plainTxt="False">
								<![CDATA[SystemUtil]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:17]]>
							</Time>
							<TimeTick>1648626017</TimeTick>
							<Step rID="T11">
								<Obj plainTxt="False">
									<![CDATA[Run "cmd",1]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA[Run "cmd",1]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:40:17]]>
								</Time>
								<TimeTick>1648626017</TimeTick>
								<NodeArgs eType="Replay" icon="7" nRep="17" status="Passed" Source="Initialisations [Initialisations] [2]" SourceLine="37">
									<Disp>
										<![CDATA[Run "cmd",1]]>
									</Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Replay" icon="7" nRep="16" status="Passed" Source="Initialisations [Initialisations] [2]" SourceLine="37">
								<Disp>
									<![CDATA[SystemUtil]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T12">
							<Obj plainTxt="False">
								<![CDATA[P9]]>
							</Obj>
							<Details plainTxt="False">
								<![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:18]]>
							</Time>
							<TimeTick>1648626018</TimeTick>
							<Step rID="T13">
								<Obj plainTxt="False">
									<![CDATA[P9.Exist]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA["Object does not exist"]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:40:18]]>
								</Time>
								<TimeTick>1648626018</TimeTick>
								<NodeArgs eType="Replay" icon="8" nRep="22" Source="Initialisations [Initialisations] [2]" SourceLine="40">
									<Disp>
										<![CDATA[P9.Exist]]>
									</Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Context" icon="8" nRep="21" Source="Initialisations [Initialisations] [2]" SourceLine="40">
								<Disp>
									<![CDATA[P9]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Action rID="T14">
							<AName>
								<![CDATA[Vidage_Cache [vidage_cache]]]>
							</AName>
							<Summary sTime="30/03/2022 - 09:40:18" eTime="30/03/2022 - 09:40:25" passed="0" failed="0" warnings="0"></Summary>
							<NodeArgs eType="StartAction" icon="5" nRep="23">
								<Disp>
									<![CDATA[Vidage_Cache [vidage_cache] Summary]]>
								</Disp>
							</NodeArgs>
						</Action>
						<Step rID="T15">
							<Obj>
								<![CDATA[1]]>
							</Obj>
							<Details>
								<![CDATA[Le robot utilisé est : SFVIA018]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:43]]>
							</Time>
							<TimeTick>1648626043</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="25" status="Passed">
								<Disp>
									<![CDATA[1]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T16">
							<Obj>
								<![CDATA[2]]>
							</Obj>
							<Details>
								<![CDATA[L'environnement utilisé est TAU1 - AGENCE]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:43]]>
							</Time>
							<TimeTick>1648626043</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="26" status="Passed">
								<Disp>
									<![CDATA[2]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T17">
							<Obj>
								<![CDATA[3]]>
							</Obj>
							<Details>
								<![CDATA[Nom_envi : TAU1]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:40:43]]>
							</Time>
							<TimeTick>1648626043</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="27" status="Passed">
								<Disp>
									<![CDATA[3]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Summary sTime="30/03/2022 - 09:40:11" eTime="30/03/2022 - 09:40:43" passed="5" failed="0" warnings="0"></Summary>
						<NodeArgs eType="StartAction" icon="5" nRep="10" status="Passed">
							<Disp>
								<![CDATA[Initialisations [Initialisations] [2] Summary]]>
							</Disp>
						</NodeArgs>
					</Action>
					<Action rID="T18">
						<AName>
							<![CDATA[LancerP9 [LancerP9] [2]]]>
						</AName>
						<Step rID="T19">
							<Obj>
								<![CDATA[Lancer P9]]>
							</Obj>
							<Details>
								<![CDATA[Permet de lancer l'application P9 si elle n'est pas en cours]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:41:07]]>
							</Time>
							<TimeTick>1648626067</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="30" status="Passed" Source="LancerP9 [LancerP9] [2]" SourceLine="6">
								<Disp>
									<![CDATA[Lancer P9]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T20">
							<Obj plainTxt="False">
								<![CDATA[P9]]>
							</Obj>
							<Details plainTxt="False">
								<![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:41:07]]>
							</Time>
							<TimeTick>1648626067</TimeTick>
							<Step rID="T21">
								<Obj plainTxt="False">
									<![CDATA[P9.Exist]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA["Object does not exist"]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:07]]>
								</Time>
								<TimeTick>1648626067</TimeTick>
								<NodeArgs eType="Replay" icon="8" nRep="35" Source="LancerP9 [LancerP9] [2]" SourceLine="13">
									<Disp>
										<![CDATA[P9.Exist]]>
									</Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Context" icon="8" nRep="34" Source="LancerP9 [LancerP9] [2]" SourceLine="13">
								<Disp>
									<![CDATA[P9]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T22">
							<Obj>
								<![CDATA[4]]>
							</Obj>
							<Details>
								<![CDATA[Recherche du login via le fichier de cas de test]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:41:07]]>
							</Time>
							<TimeTick>1648626067</TimeTick>
							<NodeArgs eType="User" icon="6" nRep="36" status="Passed">
								<Disp>
									<![CDATA[4]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Step rID="T23">
							<Obj plainTxt="False">
								<![CDATA[P9]]>
							</Obj>
							<Details plainTxt="False">
								<![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]>
							</Details>
							<Time>
								<![CDATA[30/03/2022 - 09:41:19]]>
							</Time>
							<TimeTick>1648626079</TimeTick>
							<Step rID="T24">
								<Obj plainTxt="False">
									<![CDATA[P9.Exist]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA["Object does not exist"]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:19]]>
								</Time>
								<TimeTick>1648626079</TimeTick>
								<NodeArgs eType="Replay" icon="8" nRep="41" Source="LancerP9 [LancerP9] [2]" SourceLine="175">
									<Disp>
										<![CDATA[P9.Exist]]>
									</Disp>
								</NodeArgs>
							</Step>
							<NodeArgs eType="Context" icon="8" nRep="40" Source="LancerP9 [LancerP9] [2]" SourceLine="175">
								<Disp>
									<![CDATA[P9]]>
								</Disp>
							</NodeArgs>
						</Step>
						<Action rID="T25">
							<AName>
								<![CDATA[Selection_Environnement [Selection_Environnement]]]>
							</AName>
							<Step rID="T26">
								<Obj plainTxt="False">
									<![CDATA[Accueil EVD]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:21]]>
								</Time>
								<TimeTick>1648626081</TimeTick>
								<Step rID="T27">
									<Obj plainTxt="False">
										<![CDATA[Accueil EVD.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:21]]>
									</Time>
									<TimeTick>1648626081</TimeTick>
									<NodeArgs eType="Replay" icon="8" nRep="47" Source="Selection_Environnement [Selection_Environnement]" SourceLine="37">
										<Disp>
											<![CDATA[Accueil EVD.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T28">
									<Obj plainTxt="False">
										<![CDATA[SystemUtil]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA[SystemUtil]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:21]]>
									</Time>
									<TimeTick>1648626081</TimeTick>
									<Step rID="T29">
										<Obj plainTxt="False">
											<![CDATA[Run "C:\Program Files\Internet Explorer\iexplore.exe",1]]>
										</Obj>
										<Details plainTxt="False">
											<![CDATA[Run "C:\Program Files\Internet Explorer\iexplore.exe",1]]>
										</Details>
										<Time>
											<![CDATA[30/03/2022 - 09:41:21]]>
										</Time>
										<TimeTick>1648626081</TimeTick>
										<NodeArgs eType="Replay" icon="7" nRep="51" status="Passed" Source="Selection_Environnement [Selection_Environnement]" SourceLine="48">
											<Disp>
												<![CDATA[Run "C:\Program Files\Internet Explorer\iexplore.exe",1]]>
											</Disp>
										</NodeArgs>
									</Step>
									<NodeArgs eType="Replay" icon="7" nRep="50" status="Passed" Source="Selection_Environnement [Selection_Environnement]" SourceLine="48">
										<Disp>
											<![CDATA[SystemUtil]]>
										</Disp>
									</NodeArgs>
								</Step>
								<NodeArgs eType="Context" icon="8" nRep="46" status="Passed" Source="Selection_Environnement [Selection_Environnement]" SourceLine="37">
									<Disp>
										<![CDATA[Accueil EVD]]>
									</Disp>
								</NodeArgs>
							</Step>
							<Step rID="T30">
								<Obj>
									<![CDATA[5]]>
								</Obj>
								<Details>
									<![CDATA[Lancer Internet Explorer pour Ouvrir la Liste des Environnements Disponibles]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:21]]>
								</Time>
								<TimeTick>1648626081</TimeTick>
								<NodeArgs eType="User" icon="6" nRep="52" status="Passed">
									<Disp>
										<![CDATA[5]]>
									</Disp>
								</NodeArgs>
							</Step>
							<Step rID="T31">
								<Obj plainTxt="False">
									<![CDATA[Internet Explorer]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA[Dialog]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:22]]>
								</Time>
								<TimeTick>1648626082</TimeTick>
								<Step rID="T32">
									<Obj plainTxt="False">
										<![CDATA[Internet Explorer]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA[WinObject]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:22]]>
									</Time>
									<TimeTick>1648626082</TimeTick>
									<Step rID="T33">
										<Obj plainTxt="False">
											<![CDATA[Operation_Reservee.Exist]]>
										</Obj>
										<Details plainTxt="False">
											<![CDATA["Object exists"]]>
										</Details>
										<Time>
											<![CDATA[30/03/2022 - 09:41:22]]>
										</Time>
										<TimeTick>1648626082</TimeTick>
										<NodeArgs eType="Replay" icon="11" nRep="55">
											<Disp>
												<![CDATA[Operation_Reservee.Exist]]>
											</Disp>
										</NodeArgs>
									</Step>
									<NodeArgs eType="Context" icon="10" nRep="54">
										<Disp>
											<![CDATA[Internet Explorer]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T34">
									<Obj plainTxt="False">
										<![CDATA[OK.Click]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA[]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:22]]>
									</Time>
									<TimeTick>1648626082</TimeTick>
									<NodeArgs eType="Replay" icon="12" nRep="57">
										<Disp>
											<![CDATA[OK.Click]]>
										</Disp>
									</NodeArgs>
								</Step>
								<NodeArgs eType="Context" icon="9" nRep="53">
									<Disp>
										<![CDATA[Internet Explorer]]>
									</Disp>
								</NodeArgs>
							</Step>
							<Step rID="T35">
								<Obj>
									<![CDATA[6]]>
								</Obj>
								<Details>
									<![CDATA[Fermer le message 'Cette opération est réservée à certains utilisateurs']]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:23]]>
								</Time>
								<TimeTick>1648626083</TimeTick>
								<NodeArgs eType="User" icon="6" nRep="58" status="Passed">
									<Disp>
										<![CDATA[6]]>
									</Disp>
								</NodeArgs>
							</Step>
							<Step rID="T36">
								<Obj plainTxt="False">
									<![CDATA[Profil 1 – Microsoft​]]>
								</Obj>
								<Details plainTxt="False">
									<![CDATA[Window]]>
								</Details>
								<Time>
									<![CDATA[30/03/2022 - 09:41:25]]>
								</Time>
								<TimeTick>1648626085</TimeTick>
								<Step rID="T37">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:25]]>
									</Time>
									<TimeTick>1648626085</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="63">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T38">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:26]]>
									</Time>
									<TimeTick>1648626086</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="67">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T39">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:35]]>
									</Time>
									<TimeTick>1648626095</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="71">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T40">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:46]]>
									</Time>
									<TimeTick>1648626106</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="75">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T41">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:48]]>
									</Time>
									<TimeTick>1648626108</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="79">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T42">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:50]]>
									</Time>
									<TimeTick>1648626110</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="83">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T43">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:51]]>
									</Time>
									<TimeTick>1648626111</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="85">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T44">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:53]]>
									</Time>
									<TimeTick>1648626113</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="87">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T45">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:54]]>
									</Time>
									<TimeTick>1648626114</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="89">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T46">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:55]]>
									</Time>
									<TimeTick>1648626115</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="91">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T47">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:56]]>
									</Time>
									<TimeTick>1648626116</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="93">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T48">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:58]]>
									</Time>
									<TimeTick>1648626118</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="95">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T49">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:41:59]]>
									</Time>
									<TimeTick>1648626119</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="97">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T50">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:42:00]]>
									</Time>
									<TimeTick>1648626120</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="99">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T51">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:42:02]]>
									</Time>
									<TimeTick>1648626122</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="101">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T52">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:42:03]]>
									</Time>
									<TimeTick>1648626123</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="103">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T53">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>
										<![CDATA[30/03/2022 - 09:42:04]]>
									</Time>
									<TimeTick>1648626124</TimeTick>
									<NodeArgs eType="Replay" icon="13" nRep="105">
										<Disp>
											<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
										</Disp>
									</NodeArgs>
								</Step>
								<Step rID="T54">
									<Obj plainTxt="False">
										<![CDATA[Micro_Focus_UFT_Agent.Exist]]>
									</Obj>
									<Details plainTxt="False">
										<![CDATA["Object does not exist"]]>
									</Details>
									<Time>